//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoOneTest {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Selectors : global::System.Configuration.ApplicationSettingsBase {
        
        private static Selectors defaultInstance = ((Selectors)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Selectors())));
        
        public static Selectors Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[data-qa-selector=\'filter-year\'] span")]
        public string firstRegistrationDateFromSelector {
            get {
                return ((string)(this["firstRegistrationDateFromSelector"]));
            }
            set {
                this["firstRegistrationDateFromSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select[name=\'yearRange.min\']")]
        public string firstRegistrationDateFromDropdownSelector {
            get {
                return ((string)(this["firstRegistrationDateFromDropdownSelector"]));
            }
            set {
                this["firstRegistrationDateFromDropdownSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("select[name=\'yearRange.min\'] option")]
        public string firstRegistrationDateFromDropdownOptionsSelector {
            get {
                return ((string)(this["firstRegistrationDateFromDropdownOptionsSelector"]));
            }
            set {
                this["firstRegistrationDateFromDropdownOptionsSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[data-qa-selector=\'sort-select\'] select[data-qa-selector=\'select\']")]
        public string sortDropdownSelector {
            get {
                return ((string)(this["sortDropdownSelector"]));
            }
            set {
                this["sortDropdownSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[data-qa-selector=\'sort-select\'] select[data-qa-selector=\'select\'] option")]
        public string sortDropdownOptionsSelector {
            get {
                return ((string)(this["sortDropdownOptionsSelector"]));
            }
            set {
                this["sortDropdownOptionsSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div[class^=\'totalPrice\']")]
        public string totalPricesSelector {
            get {
                return ((string)(this["totalPricesSelector"]));
            }
            set {
                this["totalPricesSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[data-qa-selector=\'spec-list\'] li:nth-child(1)")]
        public string firstRegistrationDatesSelector {
            get {
                return ((string)(this["firstRegistrationDatesSelector"]));
            }
            set {
                this["firstRegistrationDatesSelector"] = value;
            }
        }
    }
}
